import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { FileText, Scale, AlertTriangle, CheckCircle2, XCircle, Shield } from "lucide-react";
import { Navigation } from "@/components/Navigation";
import { Footer } from "@/components/Footer";

const Terms = () => {
  const sections = [
    {
      icon: CheckCircle2,
      title: "Acceptance of Terms",
      content: [
        {
          text: "By accessing and using mytuta AI ('the Service'), you accept and agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service."
        },
        {
          text: "These terms apply to all users, including students, teachers, parents, and visitors."
        },
        {
          text: "We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the new terms."
        }
      ]
    },
    {
      icon: FileText,
      title: "Service Description",
      content: [
        {
          subtitle: "For Students",
          text: "mytuta AI provides AI-powered tools to help students create revision plans, generate flashcards and quizzes, track progress, and improve study habits. The Service is provided free of charge to students."
        },
        {
          subtitle: "For Teachers",
          text: "mytuta AI provides AI-powered tools to help teachers create lesson plans, generate assessments, manage resources, and track student progress. The Service is provided on a subscription basis after a free trial."
        },
        {
          subtitle: "AI-Generated Content",
          text: "Content generated by our AI is intended as a learning aid and study tool. While we strive for accuracy, AI-generated content may contain errors and should be reviewed by users."
        }
      ]
    },
    {
      icon: Scale,
      title: "User Accounts & Responsibilities",
      content: [
        {
          subtitle: "Account Creation",
          text: "You must provide accurate information when creating an account. Students under 13 require parental consent. You are responsible for maintaining the confidentiality of your account credentials."
        },
        {
          subtitle: "Acceptable Use",
          text: "You agree to use mytuta AI only for lawful educational purposes. You will not use the Service to cheat on exams, plagiarize, or violate academic integrity policies."
        },
        {
          subtitle: "Prohibited Activities",
          text: "You may not: (a) attempt to reverse engineer our AI systems, (b) use automated systems to scrape our content, (c) share your account with others, (d) upload malicious content or viruses, (e) harass or harm other users."
        },
        {
          subtitle: "Content You Upload",
          text: "You retain ownership of materials you upload. By uploading content, you grant us a license to process and use it to provide the Service. You are responsible for ensuring you have the right to upload your content."
        }
      ]
    },
    {
      icon: AlertTriangle,
      title: "Intellectual Property",
      content: [
        {
          subtitle: "Our IP",
          text: "mytuta AI, including our AI models, algorithms, design, and content, is protected by intellectual property laws. You may not copy, modify, or distribute our technology without permission."
        },
        {
          subtitle: "Your Content",
          text: "You own your uploaded materials. We do not claim ownership of your notes, study materials, or other user-generated content."
        },
        {
          subtitle: "AI-Generated Content",
          text: "Content generated by our AI based on your inputs is available for your personal or classroom use. You may not resell or redistribute AI-generated content commercially."
        },
        {
          subtitle: "Copyright Compliance",
          text: "If you upload copyrighted materials, you must have the right to do so. We will respond to valid copyright infringement notices per DMCA guidelines."
        }
      ]
    },
    {
      icon: XCircle,
      title: "Payment & Refunds (Teachers)",
      content: [
        {
          subtitle: "Free Trial",
          text: "Teachers receive a 14-day free trial. You can cancel anytime during the trial with no charges. After the trial, your subscription begins at GH₵50/month."
        },
        {
          subtitle: "Subscription",
          text: "Subscriptions automatically renew monthly unless canceled. You can cancel anytime from your account settings. Cancellation takes effect at the end of your current billing period."
        },
        {
          subtitle: "Refunds",
          text: "We offer a 7-day money-back guarantee for paid subscriptions. Contact support@mytuta.org for refund requests. Refunds are not available after 7 days from initial payment."
        },
        {
          subtitle: "Price Changes",
          text: "We may change subscription prices with 30 days notice. Existing subscribers maintain their current rate unless they cancel and resubscribe."
        }
      ]
    },
    {
      icon: Shield,
      title: "Privacy & Data",
      content: [
        {
          subtitle: "Privacy Policy",
          text: "Your use of mytuta AI is also governed by our Privacy Policy, which describes how we collect, use, and protect your data."
        },
        {
          subtitle: "Data Security",
          text: "While we implement industry-standard security measures, no system is 100% secure. You use the Service at your own risk."
        },
        {
          subtitle: "Data Retention",
          text: "We retain your data while your account is active and for a reasonable period afterward for backup and legal purposes. You can request data deletion anytime."
        }
      ]
    },
    {
      icon: AlertTriangle,
      title: "Disclaimers & Limitations",
      content: [
        {
          subtitle: "No Warranty",
          text: "The Service is provided 'as is' without warranties of any kind. We do not guarantee that the Service will be error-free, uninterrupted, or meet your specific requirements."
        },
        {
          subtitle: "Educational Tool Only",
          text: "mytuta AI is a study aid and teaching tool. It does not replace teachers, formal education, or professional tutoring. We are not responsible for academic outcomes."
        },
        {
          subtitle: "AI Accuracy",
          text: "AI-generated content may contain errors, biases, or inaccuracies. Users should verify important information and use professional judgment."
        },
        {
          subtitle: "Third-Party Links",
          text: "Our Service may contain links to external websites. We are not responsible for the content, accuracy, or practices of third-party sites."
        }
      ]
    },
    {
      icon: Scale,
      title: "Limitation of Liability",
      content: [
        {
          text: "To the maximum extent permitted by law, mytuta shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or other intangible losses resulting from your use or inability to use the Service."
        },
        {
          text: "Our total liability for any claims related to the Service shall not exceed the amount you paid us in the 12 months before the claim (or GH₵100 if you're a free user)."
        },
        {
          text: "Some jurisdictions do not allow limitation of liability, so these limitations may not apply to you."
        }
      ]
    },
    {
      icon: XCircle,
      title: "Termination",
      content: [
        {
          subtitle: "By You",
          text: "You may terminate your account at any time from your account settings. Termination is effective immediately for free accounts, or at the end of your billing period for paid accounts."
        },
        {
          subtitle: "By Us",
          text: "We may suspend or terminate your access if you violate these terms, engage in prohibited activities, or for any other reason with notice. Serious violations may result in immediate termination without notice."
        },
        {
          subtitle: "Effect of Termination",
          text: "Upon termination, your right to use the Service ceases. We may delete your account data after a reasonable period, though we may retain some information for legal or backup purposes."
        }
      ]
    },
    {
      icon: Scale,
      title: "Governing Law & Disputes",
      content: [
        {
          subtitle: "Governing Law",
          text: "These terms are governed by the laws of Ghana. Any disputes shall be resolved in the courts of Ghana."
        },
        {
          subtitle: "Dispute Resolution",
          text: "Before filing a lawsuit, you agree to try to resolve disputes informally by contacting support@mytuta.org. We'll work with you in good faith to resolve any issues."
        },
        {
          subtitle: "Class Action Waiver",
          text: "You agree to resolve disputes individually, not as part of a class action or collective proceeding."
        }
      ]
    },
    {
      icon: FileText,
      title: "General Provisions",
      content: [
        {
          subtitle: "Entire Agreement",
          text: "These terms, together with our Privacy Policy, constitute the entire agreement between you and mytuta AI."
        },
        {
          subtitle: "Severability",
          text: "If any provision of these terms is found unenforceable, the remaining provisions continue in full effect."
        },
        {
          subtitle: "No Waiver",
          text: "Our failure to enforce any right or provision does not constitute a waiver of that right or provision."
        },
        {
          subtitle: "Assignment",
          text: "You may not transfer your rights under these terms. We may transfer our rights to any affiliate or successor."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-white">
      <Navigation />
      {/* Hero Section */}
      <section className="py-20 bg-gradient-to-br from-teal-50 to-blue-50">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto text-center space-y-6">
            <Badge variant="secondary" className="inline-flex items-center gap-2 px-4 py-2 text-sm font-medium bg-teal-100 text-teal-700 border-teal-200">
              <FileText className="w-4 h-4" />
              Terms of Service
            </Badge>
            
            <h1 className="text-5xl lg:text-6xl font-bold text-slate-900 leading-tight">
              Terms of
              <br />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-teal-600 to-blue-600">
                Service
              </span>
            </h1>
            
            <p className="text-xl text-slate-600 leading-relaxed max-w-3xl mx-auto">
              Please read these terms carefully before using mytuta AI. These terms govern your use of our platform and services.
            </p>
            
            <p className="text-sm text-slate-500">
              Last Updated: January 15, 2025
            </p>
          </div>
        </div>
      </section>

      {/* Key Points */}
      <section className="py-16 bg-white border-b border-slate-200">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto">
            <h2 className="text-3xl font-bold text-slate-900 mb-8 text-center">Key Points</h2>
            <div className="grid md:grid-cols-2 gap-6">
              <Card className="p-6 bg-gradient-to-br from-teal-50 to-teal-100 border border-teal-200">
                <CheckCircle2 className="w-8 h-8 text-teal-600 mb-4" />
                <h3 className="font-bold text-slate-900 mb-2">Free for Students</h3>
                <p className="text-sm text-slate-600">Students get full access to all features at no cost, forever.</p>
              </Card>
              
              <Card className="p-6 bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200">
                <Scale className="w-8 h-8 text-blue-600 mb-4" />
                <h3 className="font-bold text-slate-900 mb-2">Educational Use Only</h3>
                <p className="text-sm text-slate-600">Use mytuta for learning and teaching, not for cheating or academic dishonesty.</p>
              </Card>
              
              <Card className="p-6 bg-gradient-to-br from-emerald-50 to-emerald-100 border border-emerald-200">
                <Shield className="w-8 h-8 text-emerald-600 mb-4" />
                <h3 className="font-bold text-slate-900 mb-2">Your Content is Yours</h3>
                <p className="text-sm text-slate-600">You retain ownership of materials you upload. We don't share your study notes.</p>
              </Card>
              
              <Card className="p-6 bg-gradient-to-br from-orange-50 to-orange-100 border border-orange-200">
                <AlertTriangle className="w-8 h-8 text-orange-600 mb-4" />
                <h3 className="font-bold text-slate-900 mb-2">AI Content Review</h3>
                <p className="text-sm text-slate-600">Always review AI-generated content. It may contain errors or inaccuracies.</p>
              </Card>
            </div>
          </div>
        </div>
      </section>

      {/* Detailed Sections */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4">
          <div className="max-w-4xl mx-auto space-y-12">
            {sections.map((section, sectionIndex) => (
              <div key={sectionIndex}>
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-12 h-12 bg-gradient-to-br from-teal-600 to-blue-700 rounded-xl flex items-center justify-center flex-shrink-0">
                    <section.icon className="w-6 h-6 text-white" />
                  </div>
                  <h2 className="text-3xl font-bold text-slate-900">{section.title}</h2>
                </div>
                
                <div className="space-y-6 ml-16">
                  {section.content.map((item, itemIndex) => (
                    <div key={itemIndex}>
                      {item.subtitle && (
                        <h3 className="text-lg font-semibold text-slate-900 mb-2">
                          {item.subtitle}
                        </h3>
                      )}
                      <p className="text-slate-600 leading-relaxed">
                        {item.text}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Contact Section */}
      <section className="py-16 bg-gradient-to-br from-slate-50 to-slate-100">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto text-center">
            <Scale className="w-12 h-12 text-teal-600 mx-auto mb-6" />
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Questions About Terms?
            </h2>
            <p className="text-xl text-slate-600 mb-8">
              We're here to help clarify any questions about these terms of service.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                className="text-lg px-8 py-4 bg-gradient-to-r from-teal-600 to-blue-600 hover:from-teal-700 hover:to-blue-700 text-white shadow-lg hover:shadow-xl transition-all duration-300"
                onClick={() => window.location.href = 'mailto:legal@mytuta.org'}
              >
                Contact Legal Team
              </Button>
              <Button 
                size="lg" 
                variant="outline"
                className="text-lg px-8 py-4 border-2 border-slate-300 text-slate-700 hover:bg-slate-50"
                onClick={() => window.location.href = '/'}
              >
                Back to Home
              </Button>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Terms;

